/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
 #include<android/log.h>
/* Header for class com_hiverender_JNI */

#ifndef _Included_com_hiverender_JNI
#define _Included_com_hiverender_JNI
#ifdef __cplusplus

#define TAG    "myhello-jni-test" // 这个是自定义的LOG的标识
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,TAG,__VA_ARGS__) // 定义LOGD类型

extern "C" {
#endif
/*
 * Class:     com_hiverender_JNI
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_hiverender_JNI_nativeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_hiverender_JNI
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hiverender_JNI_nativeRender
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
