/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_hiverender_JNI.h>
/* Header for class com_hiverender_JNI */
// #include <GLES3/gl3.h>
// #include <EGL/egl.h>
// #include <EGL/eglext.h>
#include "AppDelegate.h"


/*
 * Class:     com_hiverender_JNI
 * Method:    nativeInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_hiverender_JNI_nativeInit(JNIEnv *, jclass, jint, jint)
{
	AppDelegate::getInstance()->run();


}

/*
 * Class:     com_hiverender_JNI
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hiverender_JNI_nativeRender(JNIEnv *, jclass)
{
	AppDelegate::getInstance()->draw();
}
